services:
  # NGINX
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/nginx/:/etc/ssl/certs/:ro
    networks:
      - network
    restart: always

  # FRONTEND
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    environment:
      - PORT=${SERVER_PORT}
    networks:
      - network
    restart: always

  # PROJECT
  project:
    build: ./backend/project
    environment:
      PORT: ${SERVER_PORT}
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@project-postgres:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - network
    depends_on:
      project-postgres:
        condition: service_healthy
      project-migrate:
        condition: service_started
    restart: always

  project-postgres:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - network
    volumes:
      - project-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: always

  project-migrate:
    image: flyway/flyway:latest
    depends_on:
      - project-postgres
    environment:
      FLYWAY_URL: jdbc:postgresql://project-postgres:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    command: -locations=filesystem:/migrations migrate
    volumes:
      - ./migrations/project:/migrations:ro
    networks:
      - network

  # USER
  user:
    build: ./backend/user
    environment:
      PORT: ${SERVER_PORT}
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@user-postgres:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - network
    depends_on:
      user-postgres:
        condition: service_healthy
      user-migrate:
        condition: service_started
    restart: always

  user-postgres:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - network
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: always

  user-migrate:
    image: flyway/flyway:latest
    depends_on:
      - user-postgres
    environment:
      FLYWAY_URL: jdbc:postgresql://user-postgres:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    command: -locations=filesystem:/migrations migrate
    volumes:
      - ./migrations/user:/migrations:ro
    networks:
      - network

  # ADMIN
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  project-postgres-data: null
  user-postgres-data: null
