services:
  # NGINX
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/nginx/server.crt:/etc/ssl/certs/server.crt:ro
      - ./ssl/nginx/server.key:/etc/ssl/private/server.key:ro
    networks:
      - network
    restart: always

  # FRONTEND
  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend/src:/app/src:ro
      - ./services/frontend/public:/app/public:ro
    networks:
      - network
    restart: always

networks:
  network:
    driver: bridge
