services:
  # NGINX
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/nginx/:/etc/ssl/certs/:ro
    networks:
      - network
    restart: always

  # FRONTEND
  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend/src:/app/src:ro
      - ./services/frontend/public:/app/public:ro
    environment:
      - PORT=${SERVER_PORT}
    networks:
      - network
    restart: always

  # PROJECT
  project:
    build: ./services/project
    environment:
      PORT: ${SERVER_PORT}
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@project-postgres:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - network
    depends_on:
      project-postgres:
        condition: service_healthy
    restart: always

  project-postgres:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - network
    volumes:
      - ./sql/project-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - project-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: always

networks:
  network:
    driver: bridge

volumes:
  project-postgres-data: null
