CREATE TABLE projects (
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL DEFAULT 'New Project'
);

CREATE TABLE project_maps (
    id INTEGER PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    map JSONB NOT NULL 
);